### ISSUE TITLE
Account getting disabled

### ISSUE THREAD

**Issue by omxpro** [Anshvar58/Windows10RDP#1]
I tried this ALOT and my acc keeps getting deleted after 15 mins

**Comment by Anshvar58** [comment]
Hi @omxpro,
I heard about your issue so try to create a new account with real email id not temp and fork it and then try to stop this workflow after you shutdown the RDP. 
Hence,  your account will not disable by github

**Comment by Anshvar58** [comment]
If then you are getting disable by github then. You tell me 😊😊

**Comment by omxpro** [comment]
> Hi @omxpro,
> I heard about your issue so try to create a new account with real email id not temp and fork it and then try to stop this workflow after you shutdown the RDP.
> Hence, your account will not disable by github

Tramp mail sucks, I never use that, I've already tried this steps
```
• create a new acc with Gmail
• browse GitHub on it for 1 hour
• turn off workflow after I shutter down my rdp
• even used 1.1.1.1 VPN/dns and still got banned :(
```

**Comment by omxpro** [comment]
> I have no solution sorry 😅😓

I think we need a GitHub acc that is like 1 - 5+ years old do you have any spare ones's?

**Comment by omxpro** [comment]
@Anshvar58 how did you run it so many times and didn't get banned? , am I getting banned cuz I have 2 accs on 1 devices???

**Comment by Anshvar58** [comment]
> > I have no solution sorry 😅😓
> 
> I think we need a GitHub acc that is like 1 - 5+ years old do you have any spare ones's?

No i didn't have any one yet this account is not old as about 1 year

**Comment by Anshvar58** [comment]
> @Anshvar58 how did you run it so many times and didn't get banned? , am I getting banned cuz I have 2 accs on 1 devices??


> @Anshvar58 how did you run it so many times and didn't get banned? , am I getting banned cuz I have 2 accs on 1 devices???

I used it So many times without getting disable by github about 2-3 times a day I don't know why but sometimes github disabled my repository but not account 😅

**Comment by omxpro** [comment]
It never disabled my repo and I tried it 9+ times for 3+ days (5 times per day)

**Comment by Anshvar58** [comment]
You can chat me on Email anshvarshney58@gmail.com

**Comment by omxpro** [comment]
Alright
